######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 5 21:43:08 2007
######################################################################

TEMPLATE = app
TARGET = soj
DESTDIR = ../bin
QT	+= sql
CONFIG += release
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += compiler.h connectsql.h daemon.h executer.h window.h
SOURCES += compiler.cpp daemon.cpp executer.cpp main.cpp window.cpp
